### ISSUE TITLE
程序闪退 NoClassDefFoundError

### ISSUE THREAD

**Issue by Sum41forever** [yiyuanliu/FlipGank#3]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/icu/util/Calendar;
  at com.yiyuanliu.flipgank.data.DataManager.getToday(DataManager.java:470)                                                                          
  at com.yiyuanliu.flipgank.data.DataManager.loadNew(DataManager.java:87)                                                                           
  at com.yiyuanliu.flipgank.fragment.GankFragment.loadNew(GankFragment.java:171)                                                                           
  at com.yiyuanliu.flipgank.fragment.GankFragment.onViewCreated(GankFragment.java:111)
  .....
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.icu.util.Calendar" on path: DexPathList[[dex file "/dat

在datamanage类里面Calendar.getInstance(); 方法 直接抛出异常 

点进去看是个抽象类
 public static Calendar getInstance() {
        throw new RuntimeException("Stub!");
    }

**Comment by yiyuanliu** [comment]
感谢反馈，`android/icu/util/Calendar`要在 Api 24 以上的机器才能使用，因为调低了 IDE 的代码检测等级，没注意到这一点。

**Comment by yiyuanliu** [comment]
已修复，见 https://github.com/yiyuanliu/FlipGank/releases
